-- indices ---------

CREATE INDEX idx_hash_ano ON tbl_time using hash (year);

CREATE INDEX idx_hash_segment ON tbl_crime using hash (segment_id);

--------------------

CREATE TABLE TBL_TIME(
    ID INT PRIMARY KEY,
    PERIOD VARCHAR(15) NULL,
    DAY INT NULL,
    MONTH INT NULL,
    YEAR INT NULL,
    WEEKDAY VARCHAR(10) NULL
);

CREATE TABLE TBL_DISTRICT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE TBL_NEIGHBORHOOD(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE TBL_VERTICE(
    ID INT PRIMARY KEY,
    LABEL INT,
    DISTRICT_ID INT,
    NEIGHBORHOOD_ID INT,
    ZONE_ID INT
);

CREATE TABLE TBL_SEGMENT(
    ID INT PRIMARY KEY,
    ONEWAY VARCHAR(15) NULL,
    LENGTH VARCHAR(50) NULL,
    FINAL_VERTICE_ID INT NULL,
    START_VERTICE_ID INT NULL
);

CREATE TABLE TBL_CRIME(
    ID INT PRIMARY KEY,
    TOTAL_FEMINICIDE INT,
    TOTAL_HOMICIDE INT,
    TOTAL_FELONY_MURDER INT,
    TOTAL_BODILY_HARM INT,
    TOTAL_THEFT_CELLPHONE INT,
    TOTAL_ARMED_ROBBERY_CELLPHONE INT,
    TOTAL_THEFT_AUTO INT,
    TOTAL_ARMED_ROBBERY_AUTO INT,
    SEGMENT_ID INT,
    TIME_ID INT
);